name: Python Auto Version Tag

on:
  push:
    branches: [ main ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Version tag
        # uses: samamorgan/action-autotag-python@master
        uses: Jorricks/action-python-autotagging@1.0.1
        with:
          path: opendbt/__version__.py
          variable: version
          github_token: ${{ secrets.GITHUB_TOKEN }}